kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-rest-service
  labels:
    app: sample-rest-service
    version: v1
    part-of: container-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-rest-service
  template:
    metadata:
      labels:
        app: sample-rest-service
        version: v1
        part-of: container-playground
    spec:
      containers:
        - name: sample-rest-service
          image: werneb/sample-rest-service:latest
          ports:
          - containerPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-time-service
  labels:
    app: sample-time-service
    version: v1
    part-of: container-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-time-service
  template:
    metadata:
      labels:
        app: sample-time-service
        version: v1
        part-of: container-playground
    spec:
      containers:
        - name: sample-time-service
          image: werneb/sample-time-service:latest
          ports:
          - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sample-rest-service
  labels:
    app: sample-rest-service
    service: sample-rest-service
    version: v1
    part-of: container-playground
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: sample-rest-service
    version: v1
---
kind: Service
apiVersion: v1
metadata:
  name: sample-time-service
  labels:
    app: sample-time-service
    service: sample-time-service
    version: v1
    part-of: container-playground
spec:
  ports:
    - protocol: TCP
      port: 8080
      name: http
  selector:
    app: sample-time-service
    version: v1