kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-rest-service
  labels:
    app: sample-rest-service
    version: v1
    part-of: container-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-rest-service
  template:
    metadata:
      labels:
        app: sample-rest-service
        version: v1
        part-of: container-playground
    spec:
      containers:
        - name: sample-rest-service
          image: werneb/sample-rest-service:1
          env:
            # Environment variables are ignored by spring jaeger integration! :(
            - name: JAEGER_ENDPOINT
              value: http://jaeger-collector.istio-system.svc:14268/api/traces
            - name: JAEGER_PROPAGATION
              value: b3
            - name: JAEGER_REPORTER_LOG_SPANS
              value: "true"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-time-service
  labels:
    app: sample-time-service
    version: v1
    part-of: container-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-time-service
  template:
    metadata:
      labels:
        app: sample-time-service
        version: v1
        part-of: container-playground
    spec:
      containers:
        - name: sample-time-service
          image: werneb/sample-time-service:1
          env:
            # Environment variables are ignored by spring jaeger integration! :(
            - name: JAEGER_ENDPOINT
              value: http://jaeger-collector.istio-system.svc:14268/api/traces
            - name: JAEGER_PROPAGATION
              value: b3
            - name: JAEGER_REPORTER_LOG_SPANS
              value: "true"
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: sample-rest-service
  labels:
    app: sample-rest-service
    service: sample-rest-service
    version: v1
    part-of: container-playground
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: sample-rest-service
    version: v1
---
kind: Service
apiVersion: v1
metadata:
  name: sample-time-service
  labels:
    app: sample-time-service
    service: sample-time-service
    version: v1
    part-of: container-playground
spec:
  ports:
    - protocol: TCP
      port: 8080
      name: http
  selector:
    app: sample-time-service
    version: v1